version: '3'
services:
  dev:
    image: node:14
    volumes:
      - nodemodules:/app/node_modules
      - .:/app
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: npm run start
    ports:
      - 4567:4567
      - 5678:5678
volumes:
  nodemodules:
    external: true